name: Pruebas Automatizadas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar el repositorio
        uses: actions/checkout@v3

      - name: 🔧 Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ⚙️ Configurar MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: '5.0'

      - name: 📦 Instalar dependencias
        run: mvn clean install

      - name: 🧪 Ejecutar pruebas
        run: mvn test

